### ISSUE TITLE
Not logging the fpm command

### ISSUE THREAD

**Issue by felixgao** [kenshoo/gradle-fpm-plugin#14]
This may not be a bug but my lack of understanding of gradle.  I have a simple build.gradle script and executed my code as 
```code
gradle -i -Penv='e2e' -q rpm
```

The build failed with the following error

{:timestamp=>"2015-09-11T18:04:25.885451-0700", :message=>"Process failed: rpmbuild failed (exit code 1). Full command was:[\"rpmbuild\", \"-bb\", \"--define\", \"buildroot /var/folders/2k/gyb20v5n4dxd31xmvsmz8l80_9zsc8/T/package-rpm-build20150911-31091-1h4rrge/BUILD\", \"--define\", \"_topdir /var/folders/2k/gyb20v5n4dxd31xmvsmz8l80_9zsc8/T/package-rpm-build20150911-31091-1h4rrge\", \"--define\", \"_sourcedir /var/folders/2k/gyb20v5n4dxd31xmvsmz8l80_9zsc8/T/package-rpm-build20150911-31091-1h4rrge\", \"--define\", \"_rpmdir /var/folders/2k/gyb20v5n4dxd31xmvsmz8l80_9zsc8/T/package-rpm-build20150911-31091-1h4rrge/RPMS\", \"--define\", \"_tmppath /var/folders/2k/gyb20v5n4dxd31xmvsmz8l80_9zsc8/T\", \"/var/folders/2k/gyb20v5n4dxd31xmvsmz8l80_9zsc8/T/package-rpm-build20150911-31091-1h4rrge/SPECS/link-rss-adapter.spec\"]", :level=>:error, :file=>"fpm/command.rb", :line=>"493", :method=>"rescue in execute"}

I am trying to debug this error but since the -i option didn't print anything on the console, I am wondering what is the right options to use to show the actual fpm command used when running the script?

Thanks

Felix

**Comment by tzachz** [comment]
@felixgao I think you'll be able to see the exact fpm command if you run gradle in debug mode (add `--debug` to command). Look for a line containing the phrase `Starting process 'command 'fpm''`, e.g.:
```
09:48:04.906 [INFO] [org.gradle.process.internal.DefaultExecHandle] Starting process 'command 'fpm''. Working directory: /home/myuser/projects/myproject/build/linux-package Command: fpm -t deb -s dir -n myproject -v 0.1.0 -C /home/myuser/projects/myproject/build/staging -f
```

**Comment by felixgao** [comment]
thanks tzachz, I did noticed a small bug after using --debug.  
In my gradle script specified multiple --directories directive and it seems the plugin only retains the last one since it is a map internally.  How would I pass multiple --directories to fpm?

**Comment by tzachz** [comment]
I'm not sure how you expect `--directories` to behave in this context, but if you're trying to include files from multiple directories in the rpm/deb package, this isn't supported out-of-the-box.
The workaround I usually use is to create a separate task that collects all the relevant files into some temporary "staging" directory, and then point the fpm-plugin to package that directory, something like:
```groovy
def stagingDir = new File(project.buildDir, "staging")

task stageArtifacts(type: Copy) {
    stagingDir.mkdirs()
    into new File(stagingDir, "/destination/path")
    from "/directory1"
    from "/directory2"
    // as many as you'd like...
}

packaging {
    baseDir = stagingDir
}

debian.dependsOn stageArtifacts
```

Let me know if that helps.

**Comment by felixgao** [comment]
I guess that is a work around.  I was using the --directories to create multiple empty directories in the hosts that can be used by my program to generate logs and data to. 

Thanks.
