### ISSUE TITLE
Too many DEBs created in a multiproject

### ISSUE THREAD

**Issue by mcandre** [kenshoo/gradle-fpm-plugin#15]
Goal: Declare the gradle fpm plugin once in the top-level `build.gradle`, but only produce packages for select child projects.

Is there a sort of NO OP configuration for `packaging` that I can define for `allprojects`/`subprojects`, and override in the child projects that I *do* want fpm to create packages for?

**Comment by mcandre** [comment]
I managed to work around this by disabling the packaging tasks for all projects at top-level `build.gradle`:

```
  tasks.withType(com.kenshoo.watership.PackagingTask) {
    dependsOn shadowJar, stageScripts
    enabled = false // Default to disabled to prevent OS packages for most, pure library projects
  }
```

And re-enabling the packaging tasks for specific child projects with their `build.gradle`s:

```
tasks.withType(com.kenshoo.watership.PackagingTask) { enabled = true }
```

**Comment by tzachz** [comment]
@mcandre your workaround makes sense. 
Alternatively, I think you can also create a separate `packaging.gradle` file with the plugin's application and configuration, e.g.:
```groovy
apply plugin: 'fpm-packaging'

packaging {
    baseDir = ...
    ...
}
``` 
And add `apply from: "packaging.gradle"` to selected modules' `build.gradle` files only.
